response = {
    "id": "resp_072378d78631a152006ab6be5e924487d2884cc5bccbeab47d",
    "created_at": 1790361182.0,
    "error": None,
    "incomplete_details": None,
    "instructions": "\nYou are a helpful AI assistant.\n\nYour goal is to provide clear, accurate, and concise answers.\nIf you are not sure about something, say so instead of making up information.\n",
    "metadata": {},
    "model": "gpt-6-luna",
    "object": "response",
    "output": [
        {
            "id": "msg_072378d78631a152006ab6be5f521c87d2a148b90944360d11",
            "content": [
                {
                    "annotations": [],
                    "text": "Hello! I can read your message loud and clear. How can I help?",
                    "type": "output_text",
                    "logprobs": [],
                }
            ],
            "role": "assistant",
            "status": "completed",
            "type": "message",
            "phase": "final_answer",
        }
    ],
    "parallel_tool_calls": True,
    "temperature": 1.0,
    "tool_choice": "auto",
    "tools": [],
    "top_p": 0.98,
    "background": False,
    "completed_at": 1790361183.0,
    "conversation": None,
    "max_output_tokens": None,
    "max_tool_calls": None,
    "moderation": None,
    "previous_response_id": None,
    "prompt": None,
    "prompt_cache_diagnostics": None,
    "prompt_cache_key": None,
    "prompt_cache_options": None,
    "prompt_cache_retention": "24h",
    "reasoning": {
        "context": "all_turns",
        "effort": "medium",
        "generate_summary": None,
        "mode": "standard",
        "summary": None,
    },
    "safety_identifier": None,
    "service_tier": "default",
    "status": "completed",
    "text": {"format": {"type": "text"}, "verbosity": "medium"},
    "top_logprobs": 0,
    "truncation": "disabled",
    "usage": {
        "input_tokens": 54,
        "input_tokens_details": {"cache_write_tokens": 0, "cached_tokens": 0},
        "output_tokens": 20,
        "output_tokens_details": {"reasoning_tokens": 0},
        "total_tokens": 74,
    },
    "user": None,
    "access_programs": None,
    "billing": {"payer": "developer"},
    "frequency_penalty": 0.0,
    "presence_penalty": 0.0,
    "store": None,
    "tool_usage": {
        "image_gen": {
            "input_tokens": 0,
            "input_tokens_details": {"image_tokens": 0, "text_tokens": 0},
            "output_tokens": 0,
            "output_tokens_details": {"image_tokens": 0, "text_tokens": 0},
            "total_tokens": 0,
        },
        "web_search": {"num_requests": 0},
    },
}
